name: Pull-Up Bot
version: "1.0"
slug: pullup_bot
description: Discord bot для аналізу підтягувань
url: "https://github.com/kklapa/pull_up_repo/pullup_bot"
image: ghcr.io/yourusername/pullup_bot:{arch}
startup: services
boot: auto
init: false
homeassistant_api: true
hassio_api: true
ports:
  8080/tcp: null
arch:
  - amd64
  - aarch64
  - armv7
map:
  - "config:rw"
options:
  bot_token: ""
  guild_id: 0
  channel_id: 0
schema:
  bot_token: str
  guild_id: int
  channel_id: int
