name: "Pull-Up Bot"
version: "1.0.0"
slug: pullup_bot
description: "Discord bot для аналізу підтягувань"
arch:
  - amd64
  - aarch64
  - armv7
url: "https://github.com/kklapa/pull_up_repo"
ports: {}
map:
  - type: share
    read_only: false
  - type: homeassistant_config
    read_only: false
    path: /config
image: "ghcr.io/kklapa/{arch}-pullup-bot"
init: false
options:
  bot_token: ""
  guild_id: 0
  channel_id: 0
schema:
  bot_token: str
  guild_id: int
  channel_id: int
